In [3]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
df=pd.read_csv('spam_ham_dataset.csv')
df

Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1           2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2           3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3           4685  spam  Subject: photoshop , windows , office . cheap ...   
4           2030   ham  Subject: re : indian springs\r\nthis deal is t...   
...          ...   ...                                                ...   
5166        1518   ham  Subject: put the 10 on the ft\r\nthe transport...   
5167         404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...   
5168        2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...   
5169        1409   ham  Subject: industrial worksheets for august 2000...   
5170        4807  spam  Subject: important online banking alert\r\ndea...   

      label_num  
0             0  
1             0  
2             0  
3             1  
4             0  
...         ...  
5166          0  
5167          0  
5168          0  
5169          0  
5170          1  

[5171 rows x 4 columns]

In [4]:
# Count 1 and 0 

df['label_num'].value_counts()

0    3672
1    1499
Name: label_num, dtype: int64

In [5]:
# Duplicate value repleace 
df.drop_duplicates(inplace=True)
df


Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1           2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2           3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3           4685  spam  Subject: photoshop , windows , office . cheap ...   
4           2030   ham  Subject: re : indian springs\r\nthis deal is t...   
...          ...   ...                                                ...   
5166        1518   ham  Subject: put the 10 on the ft\r\nthe transport...   
5167         404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...   
5168        2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...   
5169        1409   ham  Subject: industrial worksheets for august 2000...   
5170        4807  spam  Subject: important online banking alert\r\ndea...   

      label_num  
0             0  
1             0  
2             0  
3             1  
4             0  
...         ...  
5166          0  
5167          0  
5168          0  
5169          0  
5170          1  

[5171 rows x 4 columns]

In [6]:


# Count 1 and 0  Again 

df['label_num'].value_counts()

0    3672
1    1499
Name: label_num, dtype: int64

In [7]:
# Cheack Null Value 
df.isnull().sum()


Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [12]:
# separate X and Y  

x=df.text.values 
y=df.label_num.values 


# TRAIN TEST SPLIT 


from sklearn.model_selection import train_test_split 
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.3) 


# Data Preprocessing 



from sklearn.feature_extraction.text import CountVectorizer 
cv=CountVectorizer()
X_train=cv.fit_transform(xtrain)

X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
# algorithm Selection 
from sklearn.naive_bayes import MultinomialNB 
model=MultinomialNB() 
model.fit(X_train,ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [15]:
X_test=cv.transform(xtest)
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
model.score(X_test,ytest)

0.9735824742268041

In [17]:
############### CHEACK SPAM OR NOT  YOUR MAIL ##############


emails=['Hey ismali do the work for your paper','it is your buddy please do the work and enjoy later']
cv_email=cv.transform(emails)
model.predict(cv_email)

array([0, 0], dtype=int64)

In [20]:
emails=['hey tuhin da i am from chottogram and you are ???','tuhin da is great for America ','huday huday ','xxx yyyyy zzzz ']
cv_email=cv.transform(emails)
model.predict(cv_email)

array([0, 0, 0, 1], dtype=int64)

In [22]:
pred=model.predict(X_test)
pred

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score
print('Accuracy Score :' ,accuracy_score(ytest,pred))

Accuracy Score : 0.9735824742268041


In [24]:
# Confusion Matrix 
from sklearn.metrics import confusion_matrix 
print('Confusion Matrix :',confusion_matrix(ytest,pred))

Confusion Matrix : [[1103   19]
 [  22  408]]


In [26]:
##  CLASSIFICATION REPORT 
from sklearn.metrics import classification_report
print("CLASSIFICATION REPORT :")
print(classification_report(ytest,pred))

CLASSIFICATION REPORT :
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1122
           1       0.96      0.95      0.95       430

    accuracy                           0.97      1552
   macro avg       0.97      0.97      0.97      1552
weighted avg       0.97      0.97      0.97      1552

